import offer1 from "@/assets/offers/Rectangle 8 (25).png";
import offer2 from "@/assets/offers/Rectangle 8 (26).png";
import offer4 from "@/assets/offers/Rectangle 8 (27).png";
import offer3 from "@/assets/offers/Rectangle 9 (3).png";
import type { Product } from "@/types/product";

export const offerProducts: (Product & {
  originalPrice: number;
  discountPercentage: number;
})[] = [
  {
    id: "offer-1",
    name: "Frozen Mixed Vegetables",
    description: "Rich in vitamin C and antioxidants for a healthy boost.",
    price: 10.0,
    originalPrice: 12.5,
    discountPercentage: 20,
    image: offer1,
    rating: 4.5,
    category: "Frozen Food's",
    brand: "Food's",
    unit: "kg",
  },
  {
    id: "offer-2",
    name: "Frozen Mixed Vegetables",
    description: "Rich in vitamin C and antioxidants for a healthy boost.",
    price: 10.0,
    originalPrice: 12.5,
    discountPercentage: 20,
    image: offer2,
    rating: 4.5,
    category: "Frozen Food's",
    brand: "Food's",
    unit: "kg",
  },
  {
    id: "offer-3",
    name: "Frozen Mixed Vegetables",
    description: "Rich in vitamin C and antioxidants for a healthy boost.",
    price: 10.0,
    originalPrice: 12.5,
    discountPercentage: 20,
    image: offer3,
    rating: 4.5,
    category: "Frozen Food's",
    brand: "Food's",
    unit: "kg",
  },
  {
    id: "offer-4",
    name: "Frozen Mixed Vegetables",
    description: "Rich in vitamin C and antioxidants for a healthy boost.",
    price: 10.0,
    originalPrice: 12.5,
    discountPercentage: 20,
    image: offer4,
    rating: 4.5,
    category: "Frozen Food's",
    brand: "Food's",
    unit: "kg",
  },
  {
    id: "offer-5",
    name: "Frozen Mixed Vegetables",
    description: "Rich in vitamin C and antioxidants for a healthy boost.",
    price: 10.0,
    originalPrice: 12.5,
    discountPercentage: 20,
    image: offer1,
    rating: 4.5,
    category: "Frozen Food's",
    brand: "Food's",
    unit: "kg",
  },
  {
    id: "offer-6",
    name: "Frozen Mixed Vegetables",
    description: "Rich in vitamin C and antioxidants for a healthy boost.",
    price: 10.0,
    originalPrice: 12.5,
    discountPercentage: 20,
    image: offer2,
    rating: 4.5,
    category: "Frozen Food's",
    brand: "Food's",
    unit: "kg",
  },
  {
    id: "offer-7",
    name: "Frozen Mixed Vegetables",
    description: "Rich in vitamin C and antioxidants for a healthy boost.",
    price: 10.0,
    originalPrice: 12.5,
    discountPercentage: 20,
    image: offer3,
    rating: 4.5,
    category: "Frozen Food's",
    brand: "Food's",
    unit: "kg",
  },
  {
    id: "offer-8",
    name: "Frozen Mixed Vegetables",
    description: "Rich in vitamin C and antioxidants for a healthy boost.",
    price: 10.0,
    originalPrice: 12.5,
    discountPercentage: 20,
    image: offer4,
    rating: 4.5,
    category: "Frozen Food's",
    brand: "Food's",
    unit: "kg",
  },
  {
    id: "offer-9",
    name: "Frozen Mixed Vegetables",
    description: "Rich in vitamin C and antioxidants for a healthy boost.",
    price: 10.0,
    originalPrice: 12.5,
    discountPercentage: 20,
    image: offer1,
    rating: 4.5,
    category: "Frozen Food's",
    brand: "Food's",
    unit: "kg",
  },
  {
    id: "offer-10",
    name: "Frozen Mixed Vegetables",
    description: "Rich in vitamin C and antioxidants for a healthy boost.",
    price: 10.0,
    originalPrice: 12.5,
    discountPercentage: 20,
    image: offer2,
    rating: 4.5,
    category: "Frozen Food's",
    brand: "Food's",
    unit: "kg",
  },
  {
    id: "offer-11",
    name: "Frozen Mixed Vegetables",
    description: "Rich in vitamin C and antioxidants for a healthy boost.",
    price: 10.0,
    originalPrice: 12.5,
    discountPercentage: 20,
    image: offer3,
    rating: 4.5,
    category: "Frozen Food's",
    brand: "Food's",
    unit: "kg",
  },
  {
    id: "offer-12",
    name: "Frozen Mixed Vegetables",
    description: "Rich in vitamin C and antioxidants for a healthy boost.",
    price: 10.0,
    originalPrice: 12.5,
    discountPercentage: 20,
    image: offer4,
    rating: 4.5,
    category: "Frozen Food's",
    brand: "Food's",
    unit: "kg",
  },
];
